### PR TITLE
Add Object parsing

### PR DESCRIPTION
**Pull request by zaeemarshad**
This PR adds PhpSerialzable.Class and PhpSerializable.Object modules. The Object module allows PHP objects and attributes to be processed. Appropriate functions and tests have been added.

### CODE REVIEW

**Comment by zaeemarshad** [comment]
It does break the contract by changing %PhpSerializable to %PhpSerializable.Class. The defstruct can be moved to the parent module if the existing contract is to be preserved. I personally think that it's better to separate out the structs into their own modules for better future management.

**Comment by zaeemarshad** [comment]
Hey @zloyrusskiy, did you get a chance to check this out?

**Comment by zloyrusskiy** [comment]
of course, I'll look later

**Comment by zaeemarshad** [comment]
@zloyrusskiy I have updated the tests. We are now using this in our code base to process PHP serialised data and its working well for us.

**Comment by jlgeering** [comment]
the changes look reasonable to me (looking at the changes in test/php_serializer_test.exs) and I wouldn't mind updating our code to a potential new version (except for nitpicking about the name of the tests ... ;-) )

**Comment by jlgeering** [comment]
oh boy, already merged and released ... nice!

**Comment by zaeemarshad** [comment]
Cool!

**Pull request merged**
